language: node_js
branches:
  only:
    - master
    - staging
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run changelog
  - npm run semantic-release
  - git stash && git checkout -B develop && git stash pop && git add .
